name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Dozy Version
      description: What version of Dozy are you running? (e.g., 1.0.0)
      placeholder: "1.0.0"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running on? (e.g., Windows 11)
      placeholder: "Windows 11"
    validations:
      required: true
  - type: input
    id: ue_version
    attributes:
      label: Unreal Engine Version
      description: What version(s) of Unreal Engine are affected?
      placeholder: "5.4.4"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      value: |
        1. Open Dozy
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
